/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.anz.wd.accounts

import spock.lang.Specification

class AppTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new Applicaton()

        when:
        def result = app.sayHello()

        then:
        result != null
    }
}
