/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.anz.wd.accounts

import spock.lang.Specification

class AppTest extends Specification {
   def "application has a greeting"() {
        setup:
        def app = new Application()

        when:
        def result = "Hello"

        then:
        result != null
    }
}
